name = "Aeroland"
author = "Gog, PirateSee, bananapix, mnwzrd"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd653134bf59842df6b5f057869e0634bb72278211f088b51442460a3643fe6f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
