StartupEvents.registry('block', e => {
    //komatiite
    e.create('komatiite')
        .displayName('Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite')
        .noDrops()

    e.create('polished_komatiite')
        .displayName('Polished Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/polished_komatiite')
        .noDrops()

    e.create('inset_komatiite')
        .displayName('Inset Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/inset_komatiite')
        .noDrops()

    e.create('cracked_komatiite_bricks')
        .displayName('Cracked Komatiite Bricks')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/cracked_komatiite_bricks')
        .noDrops()

    e.create('komatiite_tiles')
        .displayName('Komatiite Tiles')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite_tiles')
        .noDrops()

    e.create('komatiite_bricks')
        .displayName('Komatiite Bricks')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite_bricks')
        .noDrops()


    //airstone
    e.create('airstone')
        .displayName('Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone')
        .displayName('Cobbled Airstone')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_bricks')
        .displayName('Airstone Bricks')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('inset_airstone')
        .displayName('Inset Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/inset_airstone')

    e.create('airstone_tiles')
        .displayName('Airstone Tiles')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('chiseled_airstone')
        .displayName('Chiseled Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/chiseled_airstone')

    e.create('polished_airstone')
        .displayName('Polished Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')

    //slabs
    e.create('airstone_slab', 'slab')
        .displayName('Airstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone_slab', 'slab')
        .displayName('Cobbled Airstone Slab')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_bricks_slab', 'slab')
        .displayName('Airstone Brick Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('airstone_tiles_slab', 'slab')
        .displayName('Airstone Tile Slab ')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('polished_airstone_slab', 'slab')
        .displayName('Polished Airstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')
    //stairs

    e.create('airstone_stairs','stairs')
        .displayName('Airstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone_stairs','stairs')
        .displayName('Cobbled Airstone Stairs')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_brick_stairs','stairs')
        .displayName('Airstone Brick Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('airstone_tile_stairs','stairs')
        .displayName('Airstone Tile Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('polished_airstone_stairs','stairs')
        .displayName('Polished Airstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')

    //wall
    e.create('airstone_wall','wall')
        .displayName('Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('polished_airstone_wall','wall')
        .displayName('Polished Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')

    e.create('airstone_brick_wall','wall')
        .displayName('Airstone Brick Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('cobble_airstone_wall','wall')
        .displayName('Cobbled Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    //pitchstone
    e.create('pitchstone')
        .displayName('Pitchstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone')

    e.create('cobble_pitchstone')
        .displayName('Cobbled Pitchstone')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/cobble_pitchstone')

    e.create('pitchstone_bricks')
        .displayName('Pitchstone Bricks')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_bricks')

    e.create('inset_pitchstone')
        .displayName('Inset Pitchstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/inset_pitchstone')

    e.create('pitchstone_tiles')
        .displayName('Pitchstone Tiles')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_tiles')

    e.create('chiseled_pitchstone')
        .displayName('Chiseled Pitchstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/chiseled_pitchstone')

    e.create('polished_pitchstone')
        .displayName('Polished Pitchstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/polished_pitchstone')

    //slabs
    e.create('pitchstone_slab', 'slab')
        .displayName('Pitchstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone')

    e.create('cobble_pitchstone_slab', 'slab')
        .displayName('Cobbled Pitchstone Slab')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/cobble_pitchstone')

    e.create('pitchstone_bricks_slab', 'slab')
        .displayName('Pitchstone Brick Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_bricks')

    e.create('pitchstone_tiles_slab', 'slab')
        .displayName('Pitchstone Tile Slab ')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_tiles')

    e.create('polished_pitchstone_slab', 'slab')
        .displayName('Polished Pitchstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/polished_pitchstone')
    //stairs

    e.create('pitchstone_stairs','stairs')
        .displayName('Pitchstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone')

    e.create('cobble_pitchstone_stairs','stairs')
        .displayName('Cobbled Pitchstone Stairs')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/cobble_pitchstone')

    e.create('pitchstone_brick_stairs','stairs')
        .displayName('Pitchstone Brick Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_bricks')

    e.create('pitchstone_tile_stairs','stairs')
        .displayName('Pitchstone Tile Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_tiles')

    e.create('polished_pitchstone_stairs','stairs')
        .displayName('Polished Pitchstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/polished_pitchstone')

    //wall
    e.create('pitchstone_wall','wall')
        .displayName('Pitchstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone')

    e.create('polished_pitchstone_wall','wall')
        .displayName('Polished Pitchstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/polished_pitchstone')

    e.create('pitchstone_brick_wall','wall')
        .displayName('Pitchstone Brick Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/pitchstone_bricks')

    e.create('cobble_pitchstone_wall','wall')
        .displayName('Cobbled Pitchstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/pitchstone/cobble_pitchstone')

    // counterweights
    e.create('dumbell', 'slab')
        .soundType('metal')
        .hardness(5).resistance(50)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool').requiresTool(true)
        .fullBlock(true)

    e.create('counterweight_20')
        .displayName('20kpg Counterweight')
        .soundType('metal')
        .hardness(15).resistance(100)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool').requiresTool(true)
        .fullBlock(true)

    e.create('counterweight_40')
        .displayName('40kpg Counterweight')
        .soundType('metal')
        .hardness(30).resistance(100)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool').requiresTool(true)
        .fullBlock(true)

    e.create('pontoon')
        .soundType('wood')
        .hardness(3).resistance(2)
        .tagBlock('minecraft:mineable/axe')
        .tagBlock('minecraft:needs_iron_tool').requiresTool(true)
        .fullBlock(true)

    e.create('glissant')
        .soundType('sculk')
        .hardness(2.8).resistance(2.8).slipperiness(1.1)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/glissant')

    e.create('grooved_glissant')
        .soundType('sculk')
        .hardness(2.8).resistance(2.8)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/grooved_glissant')
    // G
        e.create('g')
        .displayName('G')
        .stoneSoundType()
        .hardness(1).resistance(1)
        .fullBlock(true)
        .texture('kubejs:block/g')

        e.create('spider_eye_block') // Create a new block
        .displayName('Block of Spider Eye') // Set a custom name
        .mapColor("crimson_hyphae").soundType(SoundType.WART_BLOCK)
        .hardness(0.4) // Set hardness (affects mining time)
        .resistance(0.4) // Set resistance (to explosions, etc)
        .texture('kubejs:block/spider_eye_block')
})
