StartupEvents.registry('block', e => {
    //komatiite
    e.create('komatiite')
        .displayName('Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite')
        .noDrops()

    e.create('polished_komatiite')
        .displayName('Polished Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/polished_komatiite')
        .noDrops()

    e.create('inset_komatiite')
        .displayName('Inset Komatiite')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/inset_komatiite')
        .noDrops()

    e.create('cracked_komatiite_bricks')
        .displayName('Cracked Komatiite Bricks')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/cracked_komatiite_bricks')
        .noDrops()

    e.create('komatiite_tiles')
        .displayName('Komatiite Tiles')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite_tiles')
        .noDrops()

    e.create('komatiite_bricks')
        .displayName('Komatiite Bricks')
        .stoneSoundType()
        .hardness(50).resistance(1200)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/komatiite/komatiite_bricks')
        .noDrops()


    //airstone
    e.create('airstone')
        .displayName('Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone')
        .displayName('Cobbled Airstone')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_bricks')
        .displayName('Airstone Bricks')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('inset_airstone')
        .displayName('Inset Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/inset_airstone')

    e.create('airstone_tiles')
        .displayName('Airstone Tiles')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('chiseled_airstone')
        .displayName('Chiseled Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/chiseled_airstone')

    e.create('polished_airstone')
        .displayName('Polished Airstone')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')
    //slabs
    e.create('airstone_slab', 'slab')
        .displayName('Airstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone_slab', 'slab')
        .displayName('Cobbled Airstone Slab')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_bricks_slab', 'slab')
        .displayName('Airstone Brick Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('airstone_tiles_slab', 'slab')
        .displayName('Airstone Tile Slab ')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('polished_airstone_slab', 'slab')
        .displayName('Polished Airstone Slab')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')
    //stairs

    e.create('airstone_stairs','stairs')
        .displayName('Airstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('cobble_airstone_stairs','stairs')
        .displayName('Cobbled Airstone Stairs')
        .stoneSoundType()
        .hardness(1.4).resistance(5)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')

    e.create('airstone_brick_stairs','stairs')
        .displayName('Airstone Brick Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('airstone_tile_stairs','stairs')
        .displayName('Airstone Tile Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_tiles')

    e.create('polished_airstone_stairs','stairs')
        .displayName('Polished Airstone Stairs')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')
    //wall
    e.create('airstone_wall','wall')
        .displayName('Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone')

    e.create('polished_airstone_wall','wall')
        .displayName('Polished Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/polished_airstone')

    e.create('airstone_brick_wall','wall')
        .displayName('Airstone Brick Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/airstone_bricks')

    e.create('cobble_airstone_wall','wall')
        .displayName('Cobbled Airstone Wall')
        .stoneSoundType()
        .hardness(1.2).resistance(4)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_wodden_tool').requiresTool(true)
        .fullBlock(true)
        .texture('kubejs:block/airstone/cobble_airstone')
})
