! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
minecraft:river > null
minecraft:frozen_river > null
nomansland:blackwater_river > null
nomansland:desert_river > null
nomansland:lush_river > null
regions_unexplored:cold_river > null
regions_unexplored:muddy_river > null
regions_unexplored:tropical_river > null
