#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 23 15:10:20 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
